version: 2
general:
  branches:
    only:
     - master
     - develop
     - feature/*
     - fix/*
     - refactor/*
     - test/*
     - chore/*

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test:ci
      # build once to be sure we can build
      - run: npm run build:prod
